name: simple
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_bloc: ^3.2.0
  hydrated_bloc: ^3.0.0
  json_annotation: ^3.0.1
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  build_runner:
  freezed: ^0.10.6
  json_serializable: ^3.2.5
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
