name: crystalpuzzle
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  # curved_navigation_bar: ^0.3.1
  # curved_navigation_bar:
  #   path: ./reworked/curved_navigation_bar_reworked-0.3.1/

  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
