name: nothing
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  http: ^0.12.0+2
  equatable: ^0.6.1
  flutter_bloc: ^1.0.0
  cloud_firestore: ^0.12.9+6
  firebase_admob: ^0.9.0+9

  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
