name: nothing
description: The Nothing Project.

version: 1.0.13

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  uuid: ^3.0.1
  http: ^0.13.0
  rxdart: ^0.26.0
  flutter_bloc: ^7.0.0-nullsafety.5
  hydrated_bloc: ^7.0.0-nullsafety.3
  auto_size_text: ^3.0.0-nullsafety.0
  scoped_model: ^2.0.0-nullsafety.0
  json_annotation: ^4.0.0
  google_mobile_ads: ^0.11.0+3
  firebase_core: ^1.0.1
  flutter_hooks: ^0.16.0
  confetti: ^0.6.0-nullsafety
  flutter_vibrate: ^1.0.0
  freezed_annotation: ^0.14.0
  video_player: ^2.0.2
  url_launcher: ^6.0.2
  share: ^2.0.1
  path_provider: ^2.0.1
  cupertino_icons: ^1.0.2

  flutter:
    sdk: flutter

# flutter pub run build_runner watch --delete-conflicting-outputs
dev_dependencies:
  build_runner: ^1.11.5
  flutter_launcher_icons: ^0.9.0
  freezed: ^0.14.0+2
  json_serializable: ^4.0.2

  flutter_test:
    sdk: flutter

# issue: https://github.com/flutter/flutter/issues/62240
# dependency_overrides:
#   analyzer: "0.39.14"

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon_adaptive.png"

flutter:
  uses-material-design: true
  fonts:
    - family: Gilroy
      fonts:
        - asset: fonts/Gilroy-Bold.ttf
    - family: NothingFont
      fonts:
        - asset: fonts/NothingFont.ttf
  assets:
    - assets/onboarding1.mp4
    - assets/onboarding2.mp4
