name: nothing
description: The Nothing Project.

version: 1.0.5+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  uuid: ^2.0.4
  http: ^0.12.0+3
  rxdart: ^0.24.1
  flutter_bloc: ^6.0.0
  hydrated_bloc: ^6.0.0
  auto_size_text: ^2.1.0
  scoped_model: ^1.0.1
  json_annotation: ^3.0.1
  firebase_admob: ^0.10.3
  firebase_core: ^0.5.3
  flutter_hooks: ^0.13.1
  confetti: ^0.5.4+1
  flutter_vibrate: ^1.0.0
  freezed_annotation: ^0.12.0
  video_player: ^1.0.1
  share: ">=0.6.5+4 <2.0.0"

  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

# flutter pub run build_runner watch --delete-conflicting-outputs
dev_dependencies:
  build_runner: ^1.10.11
  flutter_launcher_icons: ^0.7.4
  freezed: ^0.12.7
  json_serializable: ^3.4.0

  flutter_test:
    sdk: flutter

# issue: https://github.com/flutter/flutter/issues/62240
# dependency_overrides:
#   analyzer: "0.39.14"

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#2e68e9"
  adaptive_icon_foreground: "assets/icon.png"

flutter:
  uses-material-design: true
  fonts:
    - family: Gilroy
      fonts:
        - asset: fonts/Gilroy-Bold.ttf
    - family: NothingFont
      fonts:
        - asset: fonts/NothingFont.ttf
  assets:
    - assets/onboarding1.mp4
    - assets/onboarding2.mp4
