name: nothing
description: The Nothing Project.

version: 1.0.5+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  uuid: ^2.0.4
  http: ^0.12.0+3
  flutter_bloc: ^3.2.0
  rxdart: ^0.23.1
  hydrated_bloc: ^3.1.0
  auto_size_text: ^2.1.0
  scoped_model: ^1.0.1
  json_annotation: ^3.0.1
  firebase_admob: ^0.9.3+2
  flutter_hooks: ^0.9.0

  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

# flutter pub run build_runner watch --delete-conflicting-outputs
dev_dependencies:
  build_runner:
  flutter_launcher_icons: ^0.7.4
  freezed: ^0.10.7
  json_serializable: ^3.3.0

  flutter_test:
    sdk: flutter

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#2e68e9"
  adaptive_icon_foreground: "assets/icon.png"

flutter:
  uses-material-design: true
  fonts:
    - family: Gilroy
      fonts:
        - asset: fonts/Gilroy-Bold.ttf
  assets:
    - assets/tutor.gif
