name: nothing
description: The Nothing Project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  uuid: ^2.0.4
  http: ^0.12.0+3
  equatable: ^1.0.1
  shared_preferences: ^0.5.6
  flutter_bloc: ^3.0.0
  rxdart: ^0.23.1

  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Gilroy
      fonts:
        - asset: fonts/Gilroy-Bold.ttf
