name: nothing
description: The Nothing Project.

version: 1.0.3+0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  uuid: ^2.0.4
  http: ^0.12.0+3
  equatable: ^1.0.1
  shared_preferences: ^0.5.6
  flutter_bloc: ^3.0.0
  rxdart: ^0.23.1
  hydrated_bloc: ^3.0.0

  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_launcher_icons: ^0.7.4
  flutter_test:
    sdk: flutter

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#2e68e9"
  adaptive_icon_foreground: "assets/icon.png"
  # ios: true
  # image_path_ios: "assets/icons/icon.png"
  # image_path_android: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/back.png
  fonts:
    - family: Gilroy
      fonts:
        - asset: fonts/Gilroy-Bold.ttf
